<?php

return [
    'solid' => [
        'fa-solid fa-kitchen-set' => 'Kitchen',
        'fa-solid fa-user-tie' => 'Professional',
        'fa-solid fa-umbrella' => 'Warranty / Protection',
        'fa-solid fa-pen-ruler' => 'Design / Planning',
        'fa-solid fa-users' => 'Customers',
        'fa-solid fa-clock-rotate-left' => 'Experience / History',
        'fa-solid fa-headset' => 'Customer Support',
        'fa-solid fa-code-branch' => 'Branch / Location',
        'fa-solid fa-phone' => 'Phone',
        'fa-solid fa-envelope' => 'Email',
        'fa-solid fa-location-dot' => 'Map Pin',
        'fa-solid fa-hammer' => 'Craftsmanship',
        'fa-solid fa-screwdriver-wrench' => 'Tools / Service',
        'fa-solid fa-ruler-combined' => 'Measurement',
        'fa-solid fa-couch' => 'Furniture',
        'fa-solid fa-door-open' => 'Doors / Cabinets',
        'fa-solid fa-sink' => 'Sink',
        'fa-solid fa-star' => 'Quality',
        'fa-solid fa-shield-halved' => 'Shield / Warranty',
        'fa-solid fa-truck' => 'Delivery',
        'fa-solid fa-handshake' => 'Partnership',
        'fa-solid fa-award' => 'Award',
        'fa-solid fa-thumbs-up' => 'Satisfaction',
        'fa-solid fa-check' => 'Checkmark',
        'fa-solid fa-gear' => 'Settings',
        'fa-solid fa-house' => 'Home',
        'fa-solid fa-building' => 'Building',
        'fa-solid fa-palette' => 'Colors / Finishes',
        'fa-solid fa-layer-group' => 'Materials',
    ],

    'brands' => [
        'fa-brands fa-facebook-f' => 'Facebook',
        'fa-brands fa-facebook' => 'Facebook (alt)',
        'fa-brands fa-instagram' => 'Instagram',
        'fa-brands fa-twitter' => 'Twitter',
        'fa-brands fa-x-twitter' => 'X (Twitter)',
        'fa-brands fa-whatsapp' => 'WhatsApp',
        'fa-brands fa-youtube' => 'YouTube',
        'fa-brands fa-linkedin-in' => 'LinkedIn',
        'fa-brands fa-tiktok' => 'TikTok',
        'fa-brands fa-snapchat' => 'Snapchat',
        'fa-brands fa-telegram' => 'Telegram',
        'fa-brands fa-pinterest' => 'Pinterest',
    ],
];
